---
debian_architecture: armhf

dhcpd_enabled: true
dnsmasq_domain: lan
dnsmasq_interfaces:
  - vlan3
dnsmasq_servers:
  - "198.50.135.212"
  - "94.16.114.254"

influxdb:
  bind_addr: "127.0.0.1:8086"
  root_dir: "/srv/influxdb"
  databases:
    - empowerd
  users:
    empowerd:
      database: empowerd

grafana:
  domain: "192.168.2.30"
  dashboards:
    - power
  home_dashboard: /srv/grafana/dashboards/power_dashboard.json
  url: grafana

networks:
  - name: eth0
    mac: "xx:Xx:xx:xx:Xx:xx"
    vlan:
      - { id: 1, name: "vlan1", address: "192.168.1.30/24" }
      - id: 2
        name: "vlan2"
        address: "192.168.2.30/24"
        gateway: "192.168.2.1"
        dns: ["192.168.2.1"]
      - { id: 3, name: "vlan3", address: "192.168.3.30/24" }

ntp_listen_addresses:
  - "192.168.3.30"

nginx_sites:
  - name: default
    template: redir_to_ssl
    listen: ["192.168.2.30"]
    server_name: "empowerd-pi.lan"
  - name: empowerd_pi
    listen: ["192.168.2.30"]
    server_name: "empowerd-pi.lan"

sshd:
  listen: ["192.168.1.30"]
  extra_config: |
    Match user pi
      AuthenticationMethods publickey
    Match all
