[package]
name = "stromd"
version = "0.1.0"
authors = ["max"]
edition = "2018"

[workspace]
members = [
#    "lib/dachs-client",
#    "lib/sma-client",
#    "lib/sml-client",
#    "lib/bresser6in1-usb",
#    "lib/battery-client"
]

[dependencies]
#dachs-client = { version = "*", path = "lib/dachs-client/" }
#sma-client = { version = "*", path = "lib/sma-client/" }
#sml-client = { version = "*", path = "lib/sml-client/" }
#bresser6in1-usb = { version = "*", path = "lib/bresser6in1-usb/" }
#battery-client = { version = "*", path = "lib/battery-client/" }

futures = "*"
slog = { version="*", features=["max_level_trace"] }
sloggers = { version="*", default_features=false }
tokio = { version=">=1.0", features=["full"] }

chrono = "*"
http-client = "6.2.0" # dependency, pin version because newer one is broken.
influxdb = { version = ">=0.3.0", features = ["derive", "h1-client", "use-serde"], default-features = false }
lazy_static = "*"
regex = "*"
reqwest = { version = "*", default-features = false }

config = { version="*", default-features=false, features=["toml"] }
daemonize = "*"
getopts = "*"
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"

#slog-async = "*"
