[package]
name = "stromd"
version = "0.1.0"
authors = ["max"]
edition = "2018"

[workspace]
members = [
    "lib/sma-client",
    "lib/dachs-client",
    "lib/slog-daemon",
    "lib/influx-derive"]

[dependencies]
dachs-client = { version = "*", path = "lib/dachs-client/" }
sma-client = { version = "*", path = "lib/sma-client/" }
slog-daemon = { version = "*", path = "lib/slog-daemon" }
influx-derive = { version = "*", path = "lib/influx-derive" }

bytes = "*"
chrono = "*"
config = { version = "*", features = ["hjson"] }
csv = "*"
daemonize = "*"
influx_db_client = "*"
lazy_static = "*"
libc = "*"
regex = "*"
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
signal-hook = "*"
slog = "*"
slog-term = "*"

#slog-async = "*"
