[package]
name = "stromd"
version = "0.1.0"
authors = ["max"]
edition = "2018"

[workspace]
members = ["lib/sma", "lib/dachs", "lib/slog-daemon"]

[dependencies]
dachs = { version = "*", path = "lib/dachs/" }
sma = { version = "*", path = "lib/sma/" }
slog-daemon = { version = "*", path = "lib/slog-daemon" }

bytes = "*"
chrono = "*"
config = { version = "*", features = ["hjson"] }
csv = "*"
daemonize = "*"
influx_db_client = "*"
lazy_static = "*"
libc = "*"
regex = "*"
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
signal-hook = "*"
slog = "*"
slog-term = "*"

#slog-async = "*"
