[package]
name = "waterd"
version = "0.1.0"
authors = ["max"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version=">=0.2.0", features=["full"] }
juniper = "*"
warp = "*"

slog = { version="*", features=["max_level_trace"] }
sloggers = { version="*", default_features=false }

jwt = "*"
hmac = "*"
sha2 = "*"
ring = "*"
base64 = "*"
rust-argon2 = "*"

serde = { version=">=1.0", features=["derive"] }
serde_json = ">=1.0"
daemonize = "*"
config = { version="*", default-features=false, features=["toml"] }
getopts = "*"

#diesel = { version="*", features=["sqlite", "r2d2"] }
#r2d2-diesel="*"
sysfs_gpio = "*"
