[package]
name = "waterd"
version = "0.1.0"
license = "GPL-3+"
description = "waterd API service"
readme = "README.md"
authors = ["Max Maisel <max.maisel@posteo.de>"]
edition = "2018"

[package.metadata.deb]
assets = [
    ["target/release/waterd", "bin/", "755"],
    ["data/waterd.conf", "etc/stromd/", "600"],
    ["data/waterd.logrotate", "etc/logrotate.d/", "644"],
]
conf-files = [
    "etc/waterd/waterd.conf"
]
changelog = "ChangeLog"
maintainer-scripts = "scripts/"

[package.metadata.deb.systemd-units]

[dependencies]
tokio = { version=">=1.0", features=["full"] }
juniper = "*"
warp = ">=0.3"

slog = { version="*", features=["max_level_trace"] }
sloggers = { version="*", default_features=false }

jwt = "*"
hmac = "*"
sha2 = "*"
ring = "*"
base64 = "*"
rust-argon2 = "*"

serde = { version=">=1.0", features=["derive"] }
serde_json = ">=1.0"
daemonize = "*"
config = { version="*", default-features=false, features=["toml"] }
getopts = "*"

#diesel = { version="*", features=["sqlite", "r2d2"] }
#r2d2-diesel="*"
sysfs_gpio = "*"
