[package]
name = "stromd"
version = "0.1.0"
authors = ["max"]
edition = "2018"

[workspace]
members = [
    "lib/dachs-client",
    "lib/influx-derive",
    "lib/slog-daemon",
    "lib/sma-client",
    "lib/sml-client",
    "lib/wh1080-usb" ]

[dependencies]
dachs-client = { version = "*", path = "lib/dachs-client/" }
influx-derive = { version = "*", path = "lib/influx-derive" }
slog-daemon = { version = "*", path = "lib/slog-daemon" }
sma-client = { version = "*", path = "lib/sma-client/" }
sml-client = { version = "*", path = "lib/sml-client/" }
wh1080-usb = { version = "*", path = "lib/wh1080-usb/" }

bytes = "*"
chrono = "*"
config = { version = "*", features = ["hjson"] }
csv = "*"
daemonize = "*"
influx_db_client = "*"
lazy_static = "*"
libc = "*"
regex = "*"
reqwest = { version = "*", default-features = false }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
signal-hook = "*"
slog = { version = "*", features = ["max_level_trace", "release_max_level_warn"] }
slog-term = "*"

#slog-async = "*"
