[package]
name = "empowerd"
version = "0.2.3"
license = "AGPL-3.0-or-later"
description = "empowers the offline smart home"
authors = ["Max Maisel <max.maisel@posteo.de>"]
readme = "README.md"
edition = "2018"

[package.metadata.deb]
assets = [
    ["target/release/empowerd", "bin/", "755"],
    ["data/empowerd.conf", "etc/empowerd/", "600"],
    ["data/empowerd.logrotate", "etc/logrotate.d/empowerd", "644"],
    ["lib/bresser6in1-usb/bresser6in1.rules", "etc/udev/rules.d/", "644"],
    ["lib/sml-client/ttyusb-meter.rules", "etc/udev/rules.d/", "644"],
]
conf-files = [
    "etc/empowerd/empowerd.conf",
    "etc/logrotate.d/empowerd"
]
changelog = "ChangeLog"
maintainer-scripts = "scripts/"

[package.metadata.deb.systemd-units]

[workspace]
members = [
    "lib/bresser6in1-usb",
    "lib/dachs-client",
    "lib/sma-client",
    "lib/sml-client",
    "lib/sunny-storage-client",
    "lib/sunspec-client",
    "lib/usb-reset"
]

[dependencies]
bresser6in1-usb = { version = "*", path = "lib/bresser6in1-usb/" }
dachs-client = { version = "*", path = "lib/dachs-client/" }
sma-client = { version = "*", path = "lib/sma-client/" }
sml-client = { version = "*", path = "lib/sml-client/" }
sunny-storage-client = { version = "*", path = "lib/sunny-storage-client/" }
sunspec-client = { version = "*", path = "lib/sunspec-client/" }
usb-reset = { version = "*", path = "lib/usb-reset/" }

futures = "*"
slog = { version=">=2.7", features=["max_level_trace", "release_max_level_debug"] }
sloggers = { version=">=1.0", default_features=false }
tokio = { version=">=1.0", features=["full"] }

chrono = "*"
influxdb = { version = "0.4.0", features = ["derive", "h1-client", "use-serde"], default-features = false }
lazy_static = "*"
regex = "*"
reqwest = { version = "*", default-features = false }

config = { version="*", default-features=false, features=["toml"] }
daemonize = "*"
getopts = "*"
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"
