[package]
name = "stromd"
version = "0.2.1"
license = "AGPL-3+"
description = "stromd data logger service"
authors = ["Max Maisel <max.maisel@posteo.de>"]
edition = "2018"

[package.metadata.deb]
assets = [
    ["target/release/stromd", "bin/", "755"],
    ["data/stromd.conf", "etc/stromd/", "600"],
    ["data/stromd.logrotate", "etc/logrotate.d/", "644"],
    ["lib/bresser6in1-usb/bresser6in1.rules", "etc/udev/rules.d/", "644"],
    ["lib/sml-client/ttyusb-meter.rules", "etc/udev/rules.d/", "644"],
]
conf-files = [
    "etc/stromd/stromd.conf"
]
changelog = "ChangeLog"
maintainer-scripts = "scripts/"

[package.metadata.deb.systemd-units]

[workspace]
members = [
    "lib/dachs-client",
    "lib/sma-client",
    "lib/sml-client",
    "lib/bresser6in1-usb",
    "lib/battery-client",
    "lib/usb-reset"
]

[dependencies]
dachs-client = { version = "*", path = "lib/dachs-client/" }
sma-client = { version = "*", path = "lib/sma-client/" }
sml-client = { version = "*", path = "lib/sml-client/" }
bresser6in1-usb = { version = "*", path = "lib/bresser6in1-usb/" }
battery-client = { version = "*", path = "lib/battery-client/" }
usb-reset = { version = "*", path = "lib/usb-reset/" }

futures = "*"
slog = { version=">=2.7", features=["max_level_trace", "release_max_level_debug"] }
sloggers = { version=">=1.0", default_features=false }
tokio = { version=">=1.0", features=["full"] }

chrono = "*"
http-client = "6.2.0" # dependency, pin version because newer one is broken.
influxdb = { version = ">=0.3.0", features = ["derive", "h1-client", "use-serde"], default-features = false }
lazy_static = "*"
regex = "*"
reqwest = { version = "*", default-features = false }

config = { version="*", default-features=false, features=["toml"] }
daemonize = "*"
getopts = "*"
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0"

[patch.crates-io]
mio-serial = { git = "https://github.com/berkowski/mio-serial.git", branch = "v4.0" }
