---
- block:
  - name: Install ntp
    apt:
      name: ntp
      state: present

  - name: Configure ntp
    template:
      src: "files/ntp.conf.j2"
      dest: "/etc/ntp.conf"
      owner: root
      group: root
      mode: 0640

  tags: ntp
  notify: Restart ntp
