[package]
name = "empowerd-migrations"
version = "0.3.2"
license = "AGPL-3.0-or-later"
authors = ["Max Maisel <max.maisel@posteo.de>"]
edition = "2018"

[dependencies]
empowerd = { version = "*", path = "../" }

clap = ">=3.1.5"
influxdb = { version = "0.4.0", features = ["derive", "h1-client", "use-serde"], default-features = false }
tokio = { version=">=1.0", features=["full"] }
