[package]
name = "empowerd-utils"

version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
slog.workspace = true
tokio.workspace = true
tokio-modbus.workspace = true
