{
 "title": "Strom",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Stromverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"meter\" WHERE $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stromerzeugung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"dachs\" WHERE $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"solar\" WHERE $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Energie",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "format": "watth",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"energy\")*-1 from \"solar\" WHERE $timeFilter GROUP BY * ORDER BY time DESC\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dachs Energie (geschätzt)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"power\")*5/60000 from \"dachs\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dachs Rückspeisung",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 16 },
   "format": "watth",
   "valueName": "delta",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"energy_produced\")*-1 from \"meter\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strom gekauft",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "format": "watth",
   "valueName": "delta",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"energy_consumed\")*-1 from \"meter\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Energie Gesamt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 18 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy\" from \"solar\" GROUP BY * ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dachs Energie Gesamt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 18 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy\" FROM \"dachs\" GROUP BY * ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dachs Rückspeisung Gesamt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 18 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy_produced\" FROM \"meter\" GROUP BY * ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strom gekauft Gesamt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 18 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy_consumed\" FROM \"meter\" GROUP BY * ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}