#!/bin/sh

adduser --home /run/empowerd --no-create-home --system empowerd ||:
usermod -a -G dialout empowerd
usermod -a -G gpio empowerd
chown empowerd /etc/empowerd/empowerd.conf
mkdir -p /var/log/empowerd
chown empowerd /var/log/empowerd

deb-systemd-helper restart logrotate.service >/dev/null || true

#DEBHELPER#
