{
 "title": "Power",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Power bought",
   "type": "graph",
   "gridPos": { "h": 13, "w": 22, "x": 1, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"meter\" WHERE $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"power\" FROM \"solar\" WHERE $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"charge\",-\"power\" FROM \"battery\" WHERE $timeFilter GROUP BY *",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar production interval",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 13 },
   "format": "watth",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT Max(\"energy\") - MIN(energy) from \"solar\" WHERE $timeFilter GROUP BY * ORDER BY time DESC\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power production",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 13 },
   "format": "watth",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"energy_produced\") - MIN(\"energy_produced\") from \"meter\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie geladen",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 13 },
   "format": "watth",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"energy_in\") - MIN(\"energy_in\") from \"battery\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power bought",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 13 },
   "format": "watth",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"energy_consumed\") - MIN(\"energy_consumed\") from \"meter\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power balance interval",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 13 },
   "format": "watth",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (MAX(\"energy_consumed\") - MIN(\"energy_consumed\")) - (MAX(\"energy_produced\") - MIN(\"energy_produced\"))  FROM \"meter\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total solar power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 1, "y": 15 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy\" from \"solar\" GROUP BY * ORDER BY time DESC LIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power sold",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 15 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy_produced\" FROM \"meter\" GROUP BY * ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie entladen",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 15 },
   "format": "watth",
   "valueName": "min",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"energy_out\") - MIN(\"energy_out\") from \"battery\" WHERE $timeFilter GROUP BY * ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power bought",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 15 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy_consumed\" FROM \"meter\" GROUP BY * ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power balance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 15 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"energy_consumed\" - \"energy_produced\" FROM \"meter\" GROUP BY * ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}