---
- hosts: empowerd-pi
  roles:
    - network
    - raspi
    - sshd
    - unattended-upgrades
    - dnsmasq
    - influxdb
    - postgres-server
    - timesync
    - grafana
    - nginx
    - ntp
    - empowerd
    - backup
