---
- name: Restart systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true

- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: true
    masked: false
    state: restarted
    daemon_reload: true
